
# The default language for sites that use this theme, this
# is set in the html `lang` attribute
language: en-GB

# The default system code, used mostly in Image Service requests
system_code: jekyll-theme-origami

# The default website name. This is set to remind people to override
# it, and also to provide a default for the demo
name: Demo Website
